<?php $_code=$this->getMethodCode() ?>
<p class="note"><span>Espera 30 minutos para ir a pagar</span></p>
<br/>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_card_identity"><?php echo $this->__('Card Identity') ?><span class="required">*</span></label>
            <input type="text" title="<?php echo $this->__('Card Identity') ?>" class="input-text required-entry validate-digits" id="<?php echo $_code ?>_card_identity" name="payment[card_identity]" value="<?php echo $this->htmlEscape($this->getInfoData('card_identity')) ?>" />
            <p class="note"><span><?php echo $this->__("Enter the digit control for validation"); ?></span></p>
        </div>
    </li>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>