<?php

$block = Mage::getBlockSingleton('ocauru/installments');
$model = Mage::getSingleton('ocauru/standard');

$att_code = $model->getAttCode();
$code = $model->getCode();

if(count($block->getInstallmentsQty())): ?>

    <div id="<?php echo $att_code; ?>">
        <span><?php echo $this->__('Oca Installments'); ?></span><br/>

    <?php foreach($block->getInstallmentsQty() as $qty): ?>
        <span><input type="radio" id="<?php echo $code.'_'.$qty; ?>" name="<?php echo $att_code; ?>" value="<?php echo $qty; ?>" /><label><?php echo $qty; ?></label></span>
    <?php endforeach; ?>
    </div>

    <script type="text/javascript">
    <!--
        if($('p_method_<?php echo $code; ?>').checked){
            $('<?php echo $att_code; ?>').up().show();
        }else{
            $('<?php echo $att_code; ?>').up().hide();
        }

        payment.addAfterInitFunction('ocauru', function(){
            if ($('oca_installment') && $('co-payment-form')){
                var form = $('co-payment-form');
                var elements = form.select('input').concat(form.select('select')).concat(form.select('textarea'));
                for (var i=0; i<elements.length; i++) elements[i].disabled = false;

                jQuery('input[name="payment[method]"]').change(function(){
                    if(jQuery(this).attr('id') == jQuery('#p_method_<?php echo $code; ?>').attr('id')) {
                        jQuery('#oca_installment').show();
                        jQuery('#oca_installment').parent().show();
                    } else {
                        jQuery('#oca_installment').hide();
                        jQuery('#oca_installment').parent().hide();
                        jQuery('#oca_installment').find('input[name=oca_installment]').attr('checked', false);
                    }
                });

            }
        });


    //-->
    </script>

<?php endif; ?>