
<script>

(function( $ ) {
  $(function() {
    // More code using $ as alias to jQuery
    PreviewDesign = function(type){
        var url;
        switch(type){
            case "order":
//                jQuery.ajax({
//                    url: "<?php echo Mage::getSingleton("adminhtml/url")->getUrl("pdfinvoiceplus/adminhtml_design/previewOrderDesign",array("id"=>$this->_id));?>",
//                    data: {form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"},
//                    crossDomain: true,
//                    success: function(data) {
//                        $.featherlight(data, {
//                            context: 'main-content'
//                        });
//                    },
//                    type: "POST"
//                });

                TINY.box.show({
                    iframe:'<?php echo Mage::getSingleton("adminhtml/url")->getUrl("pdfinvoiceplus/adminhtml_design/previewOrderDesign",array("id"=>$this->_id));?>',
                    boxid:'frameless',
                    animate: false,
                    width:850,
                    height:650,
                    fixed:false,
                    maskid:'bluemask',
                    maskopacity:40,
                    openjs:function(){},
                    closejs:function(){}
                });
                
                break;
            case "invoice":
                TINY.box.show({
                    iframe:'<?php echo Mage::getSingleton("adminhtml/url")->getUrl("pdfinvoiceplus/adminhtml_design/previewInvoiceDesign",array("id"=>$this->_id));?>',
                    boxid:'frameless',
                    animate: false,
                    width:850,
                    height:650,
                    fixed:false,
                    maskid:'bluemask',
                    maskopacity:40,
                    openjs:function(){},
                    closejs:function(){}
                });
                break;
            case "creditmemo":
                TINY.box.show({
                    iframe:'<?php echo Mage::getSingleton("adminhtml/url")->getUrl("pdfinvoiceplus/adminhtml_design/previewCreditmemoDesign",array("id"=>$this->_id));?>',
                    boxid:'frameless',
                    animate: false,
                    width:850,
                    height:650,
                    fixed:false,
                    maskid:'bluemask',
                    maskopacity:40,
                    openjs:function(){},
                    closejs:function(){}
                });
                break;
            default:
                url = '';
                break;
        }
        
    };
  });
})(jQuery);
    
</script>

