<?php 
    $barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
    $barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
    $url_barcode = '';
    if($barcode){
        if($barcode_type == 'code128') $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/default.png';
        else $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/qr.png';
    }
    if(Mage::getStoreConfig('giftvoucher/print_voucher/logo')) $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/logo/'.Mage::getStoreConfig('giftvoucher/print_voucher/logo');
    else $logo = $this->getSkinUrl('images/logo_print.gif');
?>
<div id="giftcard-template-back" style="/*display:none*/">
    <div class="giftcard-template-content" style= "display:none"></div>
    <div class="giftcard-change-image-background-popup giftcard-change-image" style="background-size: 600px 365px; background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/default.png' ?>);">
        <div class="custom-giftcard">
            <div class = "title-value giftcard-logo-background">
                    <div class="giftcard-style-color giftcard-title"><?php echo $this->__('Giftcard Title') ?></div>
                    <div class="giftcard-value-color">
                        <span class="giftcard-style-color"><?php echo $this->__('GIFT CARD - VALOR:'); ?>&nbsp;</span>
                        <span class="giftcard-style-color giftcard-price-change">$100.00</span>
                    </div>
            </div>
            <div class= "from-to-barcode-background">
                <div class = "from-to">
                    <div class = "giftcard-to" style="">
                        <label class="giftcard-text-color" for="giftcard-to"><?php echo $this->__('Para') ?>: </label>
                        <span class="giftcard-style-color giftcard-send-to" id='giftcard-to'>&nbsp;</span>
                    </div>
                    <div class = "giftcard-form">
                        <label class="giftcard-text-color" for="giftcard-from"><?php echo $this->__('De') ?>:</label>
                        <span class="giftcard-style-color giftcard-send-from" id='giftcard-from' >&nbsp;<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?></span>
                    </div>
                </div>
            </div>
            <div class = "giftcard-box-background">
                <div class = "giftcard-text-box"><pre class="giftcard-text-color giftcard-custom-message"></pre></div>
            </div>
        </div>
    </div>
</div>