<?php 
    $barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
    $barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
    $url_barcode = '';
    if($barcode){
        if($barcode_type == 'code128') $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/default.png';
        else $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/qr.png';
    }
    if(Mage::getStoreConfig('giftvoucher/print_voucher/logo')) $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/logo/'.Mage::getStoreConfig('giftvoucher/print_voucher/logo');
    else $logo = $this->getSkinUrl('images/logo_print.gif');
?>
<div id="giftcard-template-top">
    <div class="giftcard-template-content-top giftcard-change-image-temp2 giftcard-change-image" style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/top/default.png' ?>);">
         <div class="logo-title logo-title-top"></div>
         <div class = "name-value-top">
             <div class="giftcard-style-color giftcard-title"><?php echo $this->__('Giftcard Title') ?></div>
             <div  class="giftcard-value">                
                 <div class = "giftcard-style-color value-price">
                     <span><?php echo $this->__('GIFT CARD - VALOR: ') ?></span>
                     <span class="giftcard-style-color giftcard-price-change">$100.00</span>
                 </div>
             </div>
         </div>
    </div>
    <div class="giftcard-template-content" style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/top/default.png' ?>);">       
        <div class="giftcard-date-top">
            <div class="giftcard-from-to">
                <span class="giftcard-to">
                    <label  class="giftcard-text-color" for="giftcard-to"><?php echo $this->__('Para') ?>: </label>
                    <span class="giftcard-text-color giftcard-send-to">&nbsp;</span>
                </span>
                <span class="giftcard-from">
                    <label  class="giftcard-text-color" for="giftcard-from"><?php echo $this->__('De') ?>:</label>
                    <span class="giftcard-text-color giftcard-send-from">&nbsp;<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?></span>
                </span>
            </div> 
            <div class="giftcard-information">
                <div class="giftcard-message">
                    <pre class="giftcard-text-color giftcard-custom-message"></pre>
                </div>
            </div>             
        </div>
    </div>
</div>