<?php
$templateObject = $this->getDataObject();
$logo = $templateObject->getData('company_logo');
$name = $templateObject->getData('company_name');
$address = $templateObject->getData('company_address');
$phone = $templateObject->getData('company_telephone');
$email = $templateObject->getData('company_email');
$fax = $templateObject->getData('company_fax');
$businessId = $templateObject->getData('business_id');
$vatnumber = $templateObject->getData('vat_number');
$vatoffice = $templateObject->getData('vat_office');
$note = $templateObject->getData('note');
$term = $templateObject->getData('terms_conditions');
$footer = $templateObject->getData('footer');
$color = '78C145';
$pageFormat = $templateObject->getFormat();
$barcode_order = $templateObject->getBarcodeOrder();
$display_images = $templateObject->getDisplayImages();
$orientation = $templateObject->getOrientation();
if ($orientation == 0) {
    if ($pageFormat == 'A5') {
        $title_width = '82%';
        $title_arrow = '10%';
    } else {
        $title_width = '87%';
        $title_arrow = '8%';
    }
} elseif ($orientation == 1) {
    if ($pageFormat == 'A5') {
        $title_width = '84%';
        $title_arrow = '10%';
    } else {
        $title_width = '88%';
        $title_arrow = '7%';
//        $title_width = '91%';
//        $title_arrow = '5%';
    }
}
$barcode = $templateObject->getBarcode();
$barcode_type = $templateObject->getBarcodeType();
//$barcode_value = Mage::helper('pdfinvoiceplus/pdf')->getBarcodeValue();
$status = $templateObject->getStatus();
?>

<style><!--
    *{margin: 0; padding: 0;}
    body {
        font-size: 12px;
        max-width:100%;
        margin: 0 auto;
        font-family: "Ubuntu Regular", "Ubuntu Light", arial;		
        font-size-adjust: none;
        width: 100%;
    }
    #container-inner{
        position: relative;
        width: 100%;
        height: auto;
        padding: 0px;
        margin: 0 auto;
        border: 0px;
        word-wrap: normal;
    }
    .main-content {
        width:90%;
        margin: 0 5% 0;
    }
    .header-content div span{
        display: block;
        clear:left;
    }
    p {    margin: 0px;
    }
    
    table thead th { 
                    background-color: <?php echo '#' . $color; ?>;
                     color: #fff;
                     text-align: center;
                     border: 0.1mm solid #fff;
                     font-weight: bold;
                     padding: 12px 20px;
                     text-transform: uppercase;
    }
    .table-data tbody td{
        background: #E9E9E9;
        padding: 12px 10px;
        color: #2f2f2f;
        border:1px solid #fff
    }
    .items td.blanktotal {
        background-color: #FFFFFF;
        border: 0mm none #fff;
        border-top: 0.1mm solid #fff;
        border-right: 0.1mm solid #fff;
    }
    .items td.totals {
        background: none repeat scroll 0 0 #ffe9d9;
        border: 0 none;
        text-align: right;
        padding: 5px 20px;
    }
    .top-title span {
        display: block;
        font-size: 15px;
        color: #000;
    }
    .title-color{
        color: #fff;
        font-size: 14px;
        font-weight: bold;
        text-transform: uppercase;
        padding-left:20px;
        /*float:left;*/
    }

    .info-cus{
        width: 100%;
        display:inline-block;
    }
    .content{
        float: left;
        font-size: 14px;
        padding: 12px 20px;
        width: auto;
    }

    .shipping-box, .shipping-add-box{
        float:right;
    }
    .footer{

        background: #E9E9E9;
        margin-top: 50px;
        /*padding-bottom: 10px;*/
        color: #2f2f2f;
        font-size: 14px;
        text-align: left;
        position: absolute;
        bottom:0;
        width:100%;
        display:inline-block;
        border-bottom: 8px solid <?php echo '#' . $color; ?>;;
        /*margin:0 5%;*/
        /*width:90%;*/
        /*left: 5%;*/
    }

    .bottom-color{
        /*border-top :8px solid <?php echo '#' . $color ?>;*/
        border-bottom :8px solid <?php echo '#' . $color ?>;
    }
    .table-data tbody td.label{
        color: #2f2f2f;
        font-family: 'Ubuntu';
        font-weight: bold;
        font-size: 16px;
        /*width:40%;*/
        padding-right: 30%;
    }
    .table-data tfoot .grand_total td.label strong{                
        font-family: 'Ubuntu';
        font-weight: bold;
        font-size: 16px;
        line-height: 40px;
    }
    table.grandtotal td {border:0 none!important; text-align: right!important;}
    /*by viet*/
    .grand_total {
        color: #bf2323;
        font-size: 16px;
        padding: 5px;
    }
    .grand_total_value{
        color:#FF6C00;
        font-size:18px;
    }
    .order-totals{
        width:100%;
        margin-top:50px;
    }

    .order-grandtotals{
        width:55%; 
        float: right;
        background: #ffe9d9; 

        /*padding:20px;*/
    }
    .grand-label{
        font-family: 'Ubuntu';
        font-size:16px;
        padding:0px 20px;
    }
    /*            .grand-emph{
                    padding:0px 20px;
                }
                .emph-totals{
                    padding:0px 20px;
                }*/
    .barcode-order{
        /*margin-top:50px;*/
    }
    /*viet*/
    .totals{
        width:100%;
    }
    .body-total{
        width:100%;
    }
    .totals-li{
        width:100%;
        float:left;
        list-style: none outside none;
        padding: 5px 10px;
        color:#333333;
    }
    .totals-label{
        font-family: 'Ubuntu';
        font-size:16px;
        padding:0px 20px;
        color: #2F2F2F;
        font-weight: bold;
        text-align: right;
        float:left;
        height:20px;
    }
    .totals-value{
        text-align:right;
        height:20px;
        font-size: 15px;
    }
    .grand-label{
        color:#000;
    }
    .term-conditions{
        margin-top:20px;
        margin-bottom:30px;
    }
    div.arrow{
        height:0px;
        width: 0px;
        border-top: 14px solid transparent;
        border-bottom: 14px solid transparent;
        border-left: 14px solid #78C145;
        border-color: #fff #fff #fff #78C145;
    }
    div.title{
        background: <?php echo '#' . $color; ?>;
        border-radius: 0 0 0 0;    
        margin-bottom: 0;
        /*height: 14px;*/
/*        padding: 5px 0;*/
        position: relative;
        word-wrap: break-word;
        font-size: 14px;
    }
    /*********************/
    /*Totals*/
    .totals{
        float: right;
        width: 100%;
        /*            background: #e9e9e9;*/
        margin-bottom: 8px;
    }
    .body-total{
        height: auto;
        float: right;
        margin: 10px;
    }
    .total-row{
        width: 100%;
        text-align: right;
        float: right;
        padding: 5pt 0pt;
    }
    .total-row-grand{ border-top: 1px solid #e9e9e9; }
    .total-label{
        font-family: 'Ubuntu';
        font-size: 11pt;
        color: #2F2F2F;
        width: 62%;
        float: left;
        height: 22pt;
    }
    .total-value{
        font-size: 11pt;
        width: 35%;
        height: 22pt;
        float: right;
    }
    .grand-total, .grand-total-value, .grand-total-label {
        font-family: 'Ubuntu';
        font-weight: bold;
        font-size: 12pt;
    }
    .grand-total-value{
        color: #bf2323;
    }
    /*end totals*/
    /*******************/

    .note{
        padding: 10px 0;
        float: left;
    }
    .note-box{
        width: 100%;
        float: left;
    }

    .term-conditions-box [info-text]{
        float: left;
        width: 100%;
        padding: 10px 0;
    }

    /*infomations*/
    .general-info{ display: block; width:100%; float: left; font-family: 'Ubuntu Light';font-size: 15px; }
    .general-info .info-label{ font-weight: bold; display: inline-block; }
    .general-info .info-value{ display: inline-block; }
-->
    .footer-style{
        display: inline-block;
        margin: 0 5%;
        width: 90%;
    }
</style>
<div id="container-inner">
<header contextmenu-type="main" name="myheader">
    <div class="color-theme-top" style="width:100%;display: inline-block;background:#E9E9E9;padding-bottom:8px;border-top: 8px solid <?php echo '#' . $color; ?>">
        <div class="header-content" style="float:left;width:90%;margin: 0 5%;">		
            <div class='ajaxupload' style=" width:20%;height:160px;margin-top: 20px;text-align: left; float: left" info-img="company_logo"><?php echo ($logo) ? '<img width="160" src="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/logo/' . $logo . '" />' : ''; ?></div>
            <div class="autogrow" contenteditable="true" style="width:45%;color:#000;font-size: 14px;text-align: right; float: right;padding-left:22px">

                <div info-text-outer="company_name">
                    <?php if ($name): ?>
                        <p class="info-company_name color-text general-info" style="font-weight: bold; font-size: 18px; color:#00CC00; text-transform: uppercase;">
                            <span class="color-theme-text info-value" info-text="company_name"><?php echo $name ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_address">
                    <?php if ($address): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('Add'); ?> : </span>
                            <span class="info-value" info-text="company_address"><?php echo $address ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_email">
                    <?php if ($email): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('Email'); ?>: </span>
                            <span class="info-value" info-text="company_email"><?php echo $email ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_telephone">
                    <?php if ($phone): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('Tel'); ?> : </span>
                            <span class="info-value" info-text="company_telephone"><?php echo $phone ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_fax">
                    <?php if ($fax): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('Fax'); ?> : </span>
                            <span class="info-value" info-text="company_fax"><?php echo $fax ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="vat_number">
                    <?php if ($vatnumber): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('VAT Number:') ?></span>
                            <span class="info-value" info-text="vat_number"><?php echo $vatnumber ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="vat_office">
                    <?php if ($vatoffice): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('VAT Office:') ?></span>
                            <span class="info-value" info-text="vat_office"><?php echo $vatoffice ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="business_id">
                    <?php if ($businessId): ?>
                        <p class="color-text general-info">
                            <span class="info-label"><?php echo $this->__('Business Id:') ?></span>
                            <span class="info-value" info-text="business_id"><?php echo $businessId ?></span>
                        </p><?php endif; ?></div>

            </div>
            
        </div>
    </div>
</header>
<div contextmenu-type="main" id="main-content" class="main-content">
    <div class="top-title" style="width: 100%;clear: both;padding-bottom: 5px;">
        <div style="float:left;width:58%">
            <div style="width:35%;float:left">
            <div class="color-theme-text" contenteditable="true"  style="color: <?php echo '#' . $color; ?>; font-family: 'Ubuntu Regular';text-align:left; font-size: 24px;font-weight: normal; text-transform: uppercase;"><?php echo $this->_locale->translate('Order'); ?></div>
            <?php if ($status): ?><span class="color-text" contenteditable="true" style="display: block;width:100%;float: left; padding-top:0px;padding-bottom:20px"><strong><?php echo $this->__('Status:') ?> </strong>{{var order_status}}</span><br/><?php endif; ?>
            </div>
            <div class="barcode" style="float:right;text-align:left;width:65%;padding-top:5px">
                    <?php if ($barcode =='1' && $barcode_order): ?>
                        <!--<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/barcode.jpg' ?>">-->
                        <barcode code='<?php echo $barcode_order; ?>' type='<?php echo $barcode_type; ?>' />
                    <?php endif; ?>
            </div>
        </div>
        <div  style="float:left;width: 40%;">
            <div class="autogrow" style="text-align: right;float:right;">
                <span class="color-text" contenteditable="true" style="font-family: 'Ubuntu Medium';font-size: 26px;">#{{var order_increment_id}}</span><br/>
                <span class="color-text" contenteditable="true" style="color: #010101;font-size: 18px;">{{var order_created_at}}</span>
            </div>
        </div>
        
    </div>
    <div class="info-cus">				
        <div style="width:49%;float:left" class="billing-box">
            <div style="width:100%">
                <div class="title" style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" class="title-color" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Billing Address') ?></div>
                </div>
                <div class="arrow" style="width: <?php echo $title_arrow; ?>; float: left;"></div>
            </div>
            <div contenteditable="true" class="content  autogrow">
                <address >{{var order_billing_address}}</address>
            </div>
        </div>

        <div style="width:49%;float:right;margin-left: 0" class="shipping-add-box">
            <div style="width:100%">
                <div class="title" style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" class="title-color" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Shipping Address') ?></div>
                </div>
                <div class="arrow" style="width:<?php echo $title_arrow; ?>; float: left;"></div>
            </div>
            <div contenteditable="true" class="content  autogrow">
                <address >{{var order_shipping_address}}</address>
            </div>
        </div>		
    </div>

    <div style="margin-bottom: 5px;" class="">		
        <div style="width:49%;float:left;" class="payment-box">
            <div style="width:100%">
                <div class="title" style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" class="title-color" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Payment Method') ?></div>
                </div>
                <div class="arrow" style="width: <?php echo $title_arrow; ?>; float: left;"></div>
            </div>				
            <div class="content autogrow" contenteditable="true">
                {{var order_payment_method}}
            </div>
        </div>

        <div style="width:49%;float:right;" class="shipping-box">
            <div style="width:100%">
                <div class="title" style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" class="title-color" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Shipping Method') ?></div>
                </div>
                <div class="arrow" style="width: <?php echo $title_arrow; ?>; float: left;"></div>
            </div>
            <div contenteditable="true" class="content autogrow">
                {{var order_shipping_method}}
            </div>
        </div>		
    </div>

    <!--<h3 style="font-size: 12pt; color: rgb(47, 79, 78);  text-transform: uppercase;font-weight:bold">Ordered Items</h3>-->
    <table id="table-item" class="items table-data" width="100%" style="font-size: 14px; border-collapse: collapse;" cellpadding="6">
        <thead>
            <tr>
                <th class="color-theme label" contenteditable="true" width="25%" style="font-family:'Ubuntu';text-align:left;"><?php echo $this->_locale->translate('Product'); ?></th>
                <th class="color-theme label" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Price') ?></th>
                <th class="color-theme label" contenteditable="true" width="19%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Qty') ?></th>
                <th class="color-theme label" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Subtotal') ?></th>
                <th class="color-theme label" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Tax') ?></th>
                <th class="color-theme label" contenteditable="true" width="auto" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Discount') ?></th>
                <th class="color-theme label" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Row Total') ?></th>
            </tr>
        </thead>
        <tbody>
            <!-- ITEMS HERE -->
            <!--            ##productlist_start##-->
            <tr>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="left">{{var items_name}}<br/>{{var items_product_options}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_price}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">
                    {{var items_qty_ordered}}<br/>
                    {{var items_qty_invoiced}}<br>
                    {{var items_qty_refunded}}
                </td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_row_total}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_tax_amount}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_discount_amount}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_row_total}}</td>
            </tr>
            <!--            ##productlist_end##-->

    </table>
    <div class="after-item" style="width:100%;display:inline-block;margin-top:10px">
        <div class="totals autogrow" contextmenu-type="main" contenteditable="true">
            <div class="body-total" contextmenu-type="main">
                <div class="total-row">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Subtotal'); ?></div>
                    <div class="total-value color-text">{{var order_subtotal}}</div>
                </div>
                <div class="total-row">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Tax'); ?></div>
                    <div class="total-value color-text">{{var order_tax_amount}}</div>
                </div>
                <div class="total-row">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Shipping'); ?></div>
                    <div class="total-value color-text">{{var order_shipping_amount}}</div>
                </div>
                <div class="total-row total-row-grand">
                    <div class="total-label color-text grand-total"><?php echo $this->_locale->translate('Grand Total'); ?></div>
                    <div class="total-value color-text grand-total grand-total-value">{{var order_grand_total}}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="note-box autogrow">
        <?php if ($note): ?>
            <div title="Click to edit..." class="note color-text" contenteditable="true" style="" contextmenu-type="main" info-text="note">    
                <?php echo $note; ?>
            </div>
        <?php endif; ?>
    </div>

    <div class="term-conditions term-conditions-box autogrow">
        <?php if ($term): ?>
            <p title="Click to edit..." class="color-text" style="" contextmenu-type="main" contenteditable="true" info-text="terms_conditions"><?php echo $term; ?></p>
        <?php endif; ?>
    </div>
</div>
</div>

<!--        <div id="footer" contextmenu-type="main" class="footer  autogrow color-text" name="myfooter" >
            <div contenteditable="true" class="footer-text bottom-color" style="padding-top: 10px;width: 100%;padding-left: 5%;" info-text="footer">-->
    <div id="footer" contextmenu-type="main" class="footer autogrow color-theme-bottom" contenteditable="true" name="myfooter" >
        <div class="color-text footer-style" style="padding-top: 10px; display:inline-block;" info-text="footer">
            <?php if ($footer) echo $footer; ?>
        </div>
    </div>
    <script type="text/javascript">
    $(function() {
        if ($('#footer').length > 0) {
            var footer = $('#footer').height()+40;
            $('#container-inner').css('padding-bottom', footer + 'px');
        }
    });
    </script>
